<a href="https://colab.research.google.com/github/vatsal-g/First-sem-project-/blob/main/Python_for_generative_AI_and_data_science_in_shoolini_university.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 10
x

10

In [ ]:
print(x)

10


In [ ]:
 #Rules for naming of variable

# 1. Starting position of variable is letter or under score

In [ ]:
my_sub = "Data science"
print(my_sub)

Data science


In [ ]:
_mycity = "Solan"
print(_mycity)

Solan


#2. Remaining part of variable are letter, underscore or number

In [ ]:
my_sub1 = "Generative AI"
print(my_sub1)

Generative AI


In [1]:
mycity = "shimla"
print(mycity)

shimla


In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
#operater
# addition(+)
2+2

4

In [ ]:
x = 2
y = 2
z = x+y
print(z)

4


In [ ]:
#expontial(**)
2**5

32

In [ ]:
#modulus(%)
5%2

1

In [ ]:
#division(/)
4/2

2.0

In [ ]:
#floor division(//)
5//2

2

In [ ]:
5//2.2

2.0

In [ ]:
#assignment operater(=)
x = 2
print(x)

2


In [ ]:
a = 20
b = 10
print(a==b)

False


In [ ]:
print(a!=b)

True


In [ ]:
print(a>b)

True


In [ ]:
print(a<b)

False


In [ ]:
x = 10
y = 10
print(x>=y)

True


In [ ]:
print(x<=y)

True


In [ ]:
#logical operater
x = 5
print(x>2 and x<10)

True


In [ ]:
print(x>2 and x>10)

False


In [ ]:
a = 10
print(x>2 or x>10)

True


In [ ]:
a = 10
print(not(x>2 or x>10))

False


In [ ]:
my_city = "Solan"
"S" in my_city

True

In [ ]:
"Z" in my_city

False

In [ ]:
"S" not in my_city

False

In [ ]:
"Z" not in my_city

True

In [ ]:
my_city = 'Solan'
type(my_city)

str

In [ ]:
my_capital = "Shimla"
type(my_capital)

str

In [ ]:
my_state = '''Himachal Pradesh'''
type(my_state)

str

In [ ]:
my_city

'Solan'

In [ ]:
len(my_city)

5

In [ ]:
#concatenation---addition of list
list1 = [34, 67, 89]
list2 = [99, 87, 65]
my_list = list1 + list2
print(my_list)

[34, 67, 89, 99, 87, 65]


In [ ]:
#append() -add item into the list at end
my_list = [89, 76, 54]
my_list.append(100)
print(my_list)

[89, 76, 54, 100]


In [ ]:
my_list

[89, 76, 54, 100]

In [ ]:
list1 = [122, 5657, 90]
my_list.extend(list1)
print(my_list)

[89, 76, 54, 100, 122, 5657, 90]


In [ ]:
#pop --- remove the item from the list with the help of index
my_list = [23, 45, 67, 80]
my_list.pop()

80

In [ ]:
print(my_list)

[23, 45, 67]


In [ ]:
my_list.pop(0)

23

In [ ]:
my_list

[45, 67]

In [ ]:
my_list = [100, 445, 78, 90]
my_list.remove(100)
my_list

[445, 78, 90]

In [ ]:
my_list = [234, 789, 67, 45, 67, 89, 67]
my_list.index(67, 3,6)

4

In [ ]:
my_list = [3, 5, 6, 3, 4, 2, 1]
my_list.sort(reverse = True)
my_list

[6, 5, 4, 3, 3, 2, 1]

In [ ]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7, 8, 9]
my_list = [list1, list2, list3]
print(my_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
my_list[1][1]

5

In [ ]:
my_list[-2][-2]

5

In [ ]:
my_tuple = (1, 2, 3)
type(my_tuple)

tuple

In [ ]:
my_tuple = (1, 2, 3)
type(my_tuple)

tuple

In [ ]:
x = 1, 2, 3
type(x)

tuple

In [ ]:
y = ()
type(y)

tuple

In [ ]:
z = (True)
type(z)

bool

In [ ]:
a = ("solan",)
type(a)

tuple

In [ ]:
my_tuple1 = ("apple", 3.24, 8, True, None) #hetrogenius
type(my_tuple1)

tuple

In [ ]:
my_tuple2 = (89, 78, 65, 34)
type(my_tuple2)

tuple

In [ ]:
state_list = ["HP", "UP", "MP", "PUN", "DELHI"]
capital_list = ["SHM", "LK", "BH", "CHD", "ND"]
x = zip(state_list, capital_list)
x

In [ ]:
list(x)

[('HP', 'SHM'), ('UP', 'LK'), ('MP', 'BH'), ('PUN', 'CHD'), ('DELHI', 'ND')]

In [ ]:
my_tuple = (45, 78, 45, 89, 70)
my_tuple.count(45) #this method count number of perticular item

2

In [ ]:
my_tuple.index(78) #this method return index of item

1

In [ ]:
#concatenation--addition of data structure
tuple1 = (1, 3, 4)
tuple2 = (5, 6, 7)
tuple3 = tuple1 + tuple2
print(tuple3)

(1, 3, 4, 5, 6, 7)


In [ ]:
y = list(tuple3)
y

[1, 3, 4, 5, 6, 7]

In [ ]:
tuple(y)

(1, 3, 4, 5, 6, 7)

In [ ]:
#immutability
my_tuple = (1, 2, 3)
my_tuple[0] = 10

TypeError: 'tuple' object does not support item assignment

In [ ]:
#set -- collection of unique number of item, non empty set represented by curly braces and item seprated by comma
my_set = {6, 8, 9, 10}
type(my_set)

set

In [ ]:
a = " "
type(a)

str

In [ ]:
b = []
type(b)

list

In [ ]:
c = ()
type(c)

tuple

In [ ]:
d = {}
type(d)

dict

In [ ]:
empty_set = set()
type(empty_set)

set

In [ ]:
a = set()
a.add(10)
a

{10}

In [ ]:
a.add(20)
a

{10, 20}

In [ ]:
a.add(20)
a

{10, 20}

In [ ]:
my_list = [56, 90, 78, 23, 12]
print(my_list)

[56, 90, 78, 23, 12]


In [ ]:
my_set = {56, 90, 78, 23, 12}
print(my_set)

{23, 56, 90, 12, 78}


In [ ]:
my_set = {89, 45, 67, 78}
my_set.update((100, 200, 50))
print(my_set)

{67, 100, 200, 45, 78, 50, 89}


In [ ]:
my_set.remove(67)
my_set

{45, 50, 78, 89, 200}

In [ ]:
#union--all unique number of item of the set
A= {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
A.intersection(B) #comman item of the set

{4, 5}

In [ ]:
#difference
A.difference(B)

{1, 2, 3}

In [ ]:
B.difference(A)

{6, 7, 8}

In [ ]:
A.symmetric_difference(B)

{1, 2, 3, 6, 7, 8}

In [ ]:
#dictionary ---collection of key value pair,enclosed by curly braces({})
#key value pair is known as item and every item seprated by comma(,)
#key and value seprated by colan(:)
my_dict = {"HP":"SHM", "UP":"LK", "MP":"BH"}
type(my_dict)

dict

In [ ]:
#dictionay---it is mutable
#key --it is immutable
#value -- it is mutable or immutable

In [ ]:
my_dict = {"HP":"SHM", "UP":"LK", "MP":"BH"}
type(my_dict)

dict

In [ ]:
my_dict = {"Name" :"Jagat", "Marks_list": [67, 87, 56, 90]}
print(my_dict)

{'Name': 'Jagat', 'Marks_list': [67, 87, 56, 90]}


In [ ]:
my_dict = {"Name" :"Jagat", "Marks_list": [67, 87, 56, 90]}
print(my_dict)

{'Name': 'Jagat', 'Marks_list': [67, 87, 56, 90]}


In [ ]:
my_dict.update({"college":"IIT Mandi"})
print(my_dict)

{'Name': 'Jagat', 'Marks_list': [67, 87, 56, 90], 'college': 'IIT Mandi'}


In [ ]:
#keys()-- this method return the keys of your dictionary
list(my_dict.keys())

['Name', 'Marks_list', 'college']

In [ ]:
#Values()-- this method return the values of your dictionary
list(my_dict.values())

['Jagat', [67, 87, 56, 90], 'IIT Mandi']

In [ ]:
list(my_dict.items())

[('Name', 'Jagat'), ('Marks_list', [67, 87, 56, 90]), ('college', 'IIT Mandi')]

In [ ]:
my_dict["Name"]

'Jagat'

In [ ]:
my_dict.get("City", "Not found")

'Not found'

In [ ]:
#if condition:
     #Code
#elif condition:
      #code
#else:
  #code

In [ ]:
age = int(input("Enter your age :"))
if age <=21:
  print("You are too young for marriage")
elif age >= 60:
  print("You are too old for marriage")
else:
  print("we will find your perfect match")


Enter your age :29
we will find your perfect match


In [ ]:
#for loop -- apply on sequence(list, tuple, string, range())
my_city = "Solan"
for char in my_city:
  print(char)

S
o
l
a
n


In [ ]:
#indexing
for i in range(0, 5, 1):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
#indexing
my_sub = "Machine learning"
for i in range(len(my_sub)): #range(16)
  print(my_sub[i], i)

M 0
a 1
c 2
h 3
i 4
n 5
e 6
  7
l 8
e 9
a 10
r 11
n 12
i 13
n 14
g 15


In [ ]:
my_sub = "Machine learning"
for i in range(-1, -(len(my_sub)+1), -1): #range(16)
  print(my_sub[i], i)

g -1
n -2
i -3
n -4
r -5
a -6
e -7
l -8
  -9
e -10
n -11
i -12
h -13
c -14
a -15
M -16


In [ ]:
#while loop --this loop execute upto condition is true
i = 0 #initialization
while i<5: #condition
  print(i)
  i+=1 #increment
print(i)

0
1
2
3
4
5


In [ ]:
#loop control statement
i = 0
while i<5:#condition
  i+=1  #increment
  if i ==3:
    break  #break the loop
    print(i)
  else:
    print(i)

1
2


In [ ]:
i = 0
while i<5:#condition
  i+=1  #increment
  if i ==3:
    continue  #skip the current iteration
    print(i)
  else:
    print(i)

1
2
4
5


In [ ]:
i = 0
while i<5:#condition
  i+=1  #increment
  if i ==3:
    pass  #it is does nothing only pass
    print(i)
  else:
    print(i)

1
2
3
4
5


In [ ]:
#user defined function
def add(): #this function use addition of two number
  a = int(input("Enter first number: "))
  b = int(input("Enter second number: "))
  c = a+b
  print(c)
  return c

In [ ]:
print(add())

Enter first number: 2
Enter second number: 6
8
8


In [ ]:
#caculation of two number
#positional arguments
def calculation(a, b):
  add = a+b
  sub = a-b
  mul = a*b
  div = a/b
  return add, sub, mul, div



In [ ]:
calculation(5, 10)

(15, -5, 50, 0.5)

In [ ]:
#default argument, this function use addition of two numbers
def add(a = 20, b = 30):
  c = a+b
  return c


In [ ]:
print(add(90, 50))

140


In [ ]:
#keyword argument
def interest(p, r, t):
  i = (p*r*t)/100
  return i

In [ ]:
print(interest(t = 2, r = 10, p = 1000))

200.0


In [ ]:
print(interest(1000, r = 10, t = 2))

200.0


In [ ]:
print(interest(p = 1000, r = 10, 2))

SyntaxError: positional argument follows keyword argument (<ipython-input-9-82f65391e6c0>, line 1)

In [ ]:
#variable length argument
#non keyword variable length argument
def test(*args):
  print(args)
  print(type(args))
  print(len(args))

In [ ]:
test(4, 6, 7, 8, 9, 3)

(4, 6, 7, 8, 9, 3)
<class 'tuple'>
6


In [ ]:
def addition(*args):
  sum = 0
  for i in args:
    sum+=i
  return sum

In [ ]:
addition(2, 3, 10, 20, 89, 78, 56, 45, 34)

337

In [ ]:
#keyword variable length arguments
def test(**kwargs):
  print(kwargs)
  print(type(kwargs))
  print(len(kwargs))

In [ ]:
test(a = 10, b = 20, c = 30)

{'a': 10, 'b': 20, 'c': 30}
<class 'dict'>
3


In [ ]:
def pass_students(**kwargs):
  pass_student_list = []
  for name, marks in kwargs.items():
    if marks >= 35:
      pass_student_list.append(name)
  return pass_student_list

In [ ]:
pass_students(A = 30, B = 78, C = 65, D = 23)

['B', 'C']

In [ ]:
#how import numpy
import numpy as np

In [ ]:
#one dimensional array
oned_array = np.array([1, 4, 7])
print(oned_array)

[1 4 7]


In [ ]:
#two dimensional array
twod_array = np.array([[7, 8, 9],[4, 5, 6]])
print(twod_array)

[[7 8 9]
 [4 5 6]]


In [ ]:
threed_array = np.array([[[8, 9, 6],[5, 4, 3]],
                        [[9, 6, 5],[3, 4, 5]]])
print(threed_array)

[[[8 9 6]
  [5 4 3]]

 [[9 6 5]
  [3 4 5]]]


In [ ]:
#array inspection
oned_array = np.array([1, 4, 7])
print(oned_array)

[1 4 7]


In [ ]:
#shape
oned_array.shape

(3,)

In [ ]:
print(twod_array)

[[7 8 9]
 [4 5 6]]


In [ ]:
twod_array.shape

(2, 3)

In [ ]:
threed_array = np.array([[[8, 9, 6],[5, 4, 3]],
                        [[9, 6, 5],[3, 4, 5]]])
print(threed_array)

[[[8 9 6]
  [5 4 3]]

 [[9 6 5]
  [3 4 5]]]


In [ ]:
threed_array.shape

(2, 2, 3)

In [ ]:
# number of dimension of array
threed_array.ndim

3

In [ ]:
#two dimensional array
twod_array = np.array([[7, 8, 9],[4, 5, 6]])
print(twod_array)
twod_array.ndim

[[7 8 9]
 [4 5 6]]


2

In [ ]:
# how to find size of array
twod_array.size

6

In [ ]:
#how to find data type of the array
print(twod_array)
twod_array.dtype

[[7 8 9]
 [4 5 6]]


dtype('int64')

In [ ]:
#how to change data type of array
twod_array.astype(float)

array([[7., 8., 9.],
       [4., 5., 6.]])

In [ ]:
#  how to create zero element array
zeros_array = np.zeros((3, 4), dtype = int)
print(zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
ones_array = np.ones((3, 4), dtype = int)*100
print(ones_array)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
my_array = np.full((3, 4), 100)
print(my_array)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
